[package]
name = "concrete_analysis"
version = "0.1.0"
authors = ["xaresti001 <xaresti001@ikasle.ehu.eus>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
concrete_lib = "0.1.0"
itertools = "0.9.0"
